import { NextResponse } from "next/server";
import { requireUserTenantApi } from "@/lib/auth";
import { assertTenantUser } from "@/lib/access";
import { createPromptPack, bulkCreatePromptItems } from "@/lib/data/prompts";

interface GeneratedPrompt {
  concept: string;
  prompt_text: string;
  tags: string[];
}

export async function POST(request: Request) {
  const auth = await requireUserTenantApi();
  if ("error" in auth)
    return NextResponse.json({ error: auth.error }, { status: auth.status });

  const allowed = await assertTenantUser(auth.tenant.id, auth.user.id);
  if (!allowed)
    return NextResponse.json({ error: "Unauthorized" }, { status: 403 });

  const body = (await request.json()) as {
    brandName: string;
    brandStyle?: string;
    shooting: string;
    goals?: string;
    count?: number;
    packName?: string;
    // Legacy support
    brief?: string;
  };

  // Support both new structured fields and legacy single brief
  const hasBrandFields = body.brandName?.trim() && body.shooting?.trim();
  const hasLegacyBrief = body.brief?.trim();

  if (!hasBrandFields && !hasLegacyBrief) {
    return NextResponse.json(
      { error: "Brand name and what you're shooting are required" },
      { status: 400 }
    );
  }

  const count = Math.min(Math.max(body.count || 20, 5), 50);
  const apiKey = process.env.GROK_API_KEY;

  if (!apiKey) {
    return NextResponse.json(
      { error: "Grok API key not configured. Add GROK_API_KEY to your environment variables." },
      { status: 500 }
    );
  }

  // Build the brief from structured fields or use legacy
  let composedBrief: string;
  let briefSummary: string;

  if (hasBrandFields) {
    const parts: string[] = [];
    parts.push(`Brand: ${body.brandName!.trim()}`);
    if (body.brandStyle?.trim()) {
      parts.push(`Style/Vibe: ${body.brandStyle.trim()}`);
    }
    parts.push(`Shooting: ${body.shooting!.trim()}`);
    if (body.goals?.trim()) {
      parts.push(`Goals: ${body.goals.trim()}`);
    }
    composedBrief = parts.join("\n");
    briefSummary = `${body.brandName!.trim()} — ${body.shooting!.trim().slice(0, 60)}`;
  } else {
    composedBrief = body.brief!.trim();
    briefSummary = composedBrief.slice(0, 60);
  }

  try {
    // Call xAI Grok API to generate prompts
    const systemPrompt = `You are an expert AI image prompt engineer for advertising and e-commerce creative production.
You generate detailed, production-ready image generation prompts based on brand briefs.

You deeply understand how to translate a brand's identity, style, and product into visual concepts that look stunning when generated by AI image models.

Each prompt should include:
- A short "concept" name (2-5 words describing the shot type or angle)
- A detailed "prompt_text" that an AI image generator can use to create the image. This should be specific, vivid, and production-ready — include camera angle, lighting, composition, setting, mood, and styling details.
- Relevant "tags" for categorization

Your prompts should cover a variety of:
- Camera angles (front, side, overhead, low angle, close-up, wide, 3/4, detail)
- Lighting styles (natural, studio, dramatic, soft, golden hour, moody, editorial)
- Compositions (hero shot, lifestyle, flat lay, detail close-up, action, editorial, environmental)
- Settings/backgrounds appropriate to the brand identity and brief
- Model diversity and styling where applicable

Make each prompt unique and varied. Ensure the prompts feel cohesive as a collection — like they belong to the same shoot for the same brand. Include specific details about styling, mood, props, color palette, and environment that match the brand identity.
The prompt_text should be 2-4 sentences, detailed enough for high-quality AI image generation.`;

    const userPrompt = `Generate exactly ${count} image generation prompts based on this creative brief:

${composedBrief}

Respond with ONLY a JSON array of objects, each with "concept" (string), "prompt_text" (string), and "tags" (string array). No markdown, no explanation, just the JSON array.

Example format:
[{"concept":"Hero Front Shot","prompt_text":"A professional studio photograph of...","tags":["studio","front","hero"]}]`;

    const grokResponse = await fetch("https://api.x.ai/v1/chat/completions", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        model: "grok-4-latest",
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user", content: userPrompt },
        ],
        temperature: 0.8,
      }),
    });

    if (!grokResponse.ok) {
      const errText = await grokResponse.text();
      console.error("[generate] Grok API error:", grokResponse.status, errText);
      return NextResponse.json(
        {
          error: "Failed to generate prompts from AI",
          detail: `Grok API returned ${grokResponse.status}`,
        },
        { status: 502 }
      );
    }

    const grokData = await grokResponse.json();
    const rawContent =
      grokData.choices?.[0]?.message?.content?.trim() ?? "";

    // Parse the JSON response — strip markdown fences if present
    let cleaned = rawContent;
    if (cleaned.startsWith("```")) {
      cleaned = cleaned.replace(/^```(?:json)?\n?/, "").replace(/\n?```$/, "");
    }

    let generatedPrompts: GeneratedPrompt[];
    try {
      generatedPrompts = JSON.parse(cleaned);
    } catch {
      console.error("[generate] Failed to parse Grok response:", rawContent.substring(0, 500));
      return NextResponse.json(
        {
          error: "Failed to parse AI response",
          detail: "The AI returned an unexpected format. Please try again.",
        },
        { status: 502 }
      );
    }

    // Validate the array
    if (!Array.isArray(generatedPrompts) || generatedPrompts.length === 0) {
      return NextResponse.json(
        { error: "AI returned empty results. Please try again." },
        { status: 502 }
      );
    }

    // Sanitize each prompt
    const validPrompts = generatedPrompts
      .filter((p) => p.concept && p.prompt_text)
      .map((p) => ({
        concept: String(p.concept).slice(0, 200),
        prompt_text: String(p.prompt_text).slice(0, 2000),
        tags: Array.isArray(p.tags)
          ? p.tags.map((t: unknown) => String(t)).slice(0, 10)
          : [],
      }));

    if (validPrompts.length === 0) {
      return NextResponse.json(
        { error: "AI did not return any valid prompts" },
        { status: 502 }
      );
    }

    // Create the prompt pack
    const packName =
      body.packName?.trim() ||
      `AI Generated — ${briefSummary}`;

    const pack = await createPromptPack(auth.tenant.id, {
      name: packName,
      description: composedBrief,
      tags: ["ai-generated"],
    });

    // Bulk create all generated items
    const itemCount = await bulkCreatePromptItems(pack.id, validPrompts);

    return NextResponse.json(
      {
        pack,
        itemCount,
        promptCount: validPrompts.length,
      },
      { status: 201 }
    );
  } catch (error) {
    console.error("[generate POST]", error);
    const message =
      error instanceof Error ? error.message : "Unknown error";
    return NextResponse.json(
      { error: "Failed to generate prompts", detail: message },
      { status: 500 }
    );
  }
}
