import { NextResponse } from "next/server";
import { requireUserTenantApi } from "@/lib/auth";
import { assertTenantUser } from "@/lib/access";
import { createBatchRun, createBatchItems } from "@/lib/data/batches";
import { getProfile } from "@/lib/data/profiles";
import { getClient } from "@/lib/data/clients";
import { buildMasterContextString } from "@/lib/data/brand-context";

function errMsg(e: unknown): string {
  if (e instanceof Error) return e.message;
  if (e && typeof e === "object") {
    const obj = e as Record<string, unknown>;
    if (typeof obj.message === "string") return obj.message;
    if (typeof obj.details === "string")
      return `${obj.message ?? "error"}: ${obj.details}`;
    try {
      return JSON.stringify(e);
    } catch {
      /* fallback */
    }
  }
  return String(e);
}

interface GeneratedPrompt {
  concept: string;
  prompt_text: string;
  tags: string[];
}

/**
 * Generate prompts from client brand context using Grok AI.
 */
async function generatePromptsFromClient(
  brandContext: string,
  clientName: string,
  count: number
): Promise<GeneratedPrompt[]> {
  const apiKey = process.env.GROK_API_KEY;
  if (!apiKey) {
    throw new Error("GROK_API_KEY not configured");
  }

  const systemPrompt = `You are an expert AI image prompt engineer for advertising and e-commerce creative production.

You generate detailed, production-ready image generation prompts based on brand context data.
You deeply understand how to translate a brand's identity, style, and product into visual concepts that look stunning when generated by AI image models.

Each prompt should include:
- A short "concept" name (2-5 words describing the shot type or angle)
- A detailed "prompt_text" that an AI image generator can use to create the image. This should be specific, vivid, and production-ready - include camera angle, lighting, composition, setting, mood, and styling details.
- Relevant "tags" for categorization

Your prompts should cover a variety of:
- Camera angles (front, side, overhead, low angle, close-up, wide, 3/4, detail)
- Lighting styles (natural, studio, dramatic, soft, golden hour, moody, editorial)
- Compositions (hero shot, lifestyle, flat lay, detail close-up, action, editorial, environmental)
- Settings/backgrounds appropriate to the brand identity
- Model diversity and styling where applicable

Make each prompt unique and varied. Ensure the prompts feel cohesive as a collection - like they belong to the same shoot for the same brand. Include specific details about styling, mood, props, color palette, and environment that match the brand identity. The prompt_text should be 2-4 sentences, detailed enough for high-quality AI image generation.`;

  const userPrompt = `Generate exactly ${count} image generation prompts for the brand "${clientName}" based on this brand context:

${brandContext}

Respond with ONLY a JSON array of objects, each with "concept" (string), "prompt_text" (string), and "tags" (string array). No markdown, no explanation, just the JSON array.`;

  const grokResponse = await fetch("https://api.x.ai/v1/chat/completions", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${apiKey}`,
    },
    body: JSON.stringify({
      model: "grok-4-latest",
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: userPrompt },
      ],
      temperature: 0.8,
    }),
  });

  if (!grokResponse.ok) {
    const errText = await grokResponse.text();
    console.error(
      "[smart-batch] Grok API error:",
      grokResponse.status,
      errText
    );
    throw new Error(`Grok API returned ${grokResponse.status}`);
  }

  const grokData = await grokResponse.json();
  const rawContent =
    grokData.choices?.[0]?.message?.content?.trim() ?? "";

  // Parse JSON - strip markdown fences if present
  let cleaned = rawContent;
  if (cleaned.startsWith("\`\`\`")) {
    cleaned = cleaned
      .replace(/^\`\`\`(?:json)?\n?/, "")
      .replace(/\n?\`\`\`$/, "");
  }

  const parsed: GeneratedPrompt[] = JSON.parse(cleaned);

  if (!Array.isArray(parsed) || parsed.length === 0) {
    throw new Error("AI returned empty results");
  }

  return parsed
    .filter((p) => p.concept && p.prompt_text)
    .map((p) => ({
      concept: String(p.concept).slice(0, 200),
      prompt_text: String(p.prompt_text).slice(0, 2000),
      tags: Array.isArray(p.tags)
        ? p.tags.map((t: unknown) => String(t)).slice(0, 10)
        : [],
    }));
}

export async function POST(request: Request) {
  const auth = await requireUserTenantApi();
  if ("error" in auth) {
    return NextResponse.json({ error: auth.error }, { status: auth.status });
  }

  const allowed = await assertTenantUser(auth.tenant.id, auth.user.id);
  if (!allowed) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 403 });
  }

  const body = (await request.json()) as {
    clientId?: string;
    profileId?: string;
    aspectRatio?: string;
    resolution?: string;
    quantity?: number;
    selectedAngles?: string[];
    lockAngles?: boolean;
  };

  if (!body.clientId || !body.profileId) {
    return NextResponse.json(
      { error: "Missing required fields: clientId, profileId" },
      { status: 400 }
    );
  }

  // Extract angle engine settings from body
  const selectedAngles: string[] = Array.isArray(body.selectedAngles)
    ? body.selectedAngles
    : [];
  const lockAngles: boolean = body.lockAngles === true;

  try {
    // Verify resources exist
    let client, profile;
    try {
      [client, profile] = await Promise.all([
        getClient(auth.tenant.id, body.clientId),
        getProfile(auth.tenant.id, body.profileId),
      ]);
    } catch (lookupErr) {
      console.error("[smart-batch] Resource lookup error:", lookupErr);
      return NextResponse.json(
        { error: `Resource lookup failed: ${errMsg(lookupErr)}` },
        { status: 500 }
      );
    }

    if (!client || !profile) {
      return NextResponse.json(
        {
          error: `Not found: ${!client ? "client" : ""} ${!profile ? "profile" : ""}`.trim(),
        },
        { status: 404 }
      );
    }

    // Build brand context string from client data
    let masterContext = "";
    try {
      masterContext =
        (await buildMasterContextString(auth.tenant.id, body.clientId)) ||
        "";
    } catch (ctxErr) {
      console.error("[smart-batch] Brand context error:", ctxErr);
    }

    if (!masterContext) {
      return NextResponse.json(
        {
          error:
            "No brand context found for this client. Please complete the Client Generator first.",
        },
        { status: 400 }
      );
    }

    const quantity = Math.min(Math.max(body.quantity || 5, 1), 20);

    // Generate prompts from client brand context using Grok AI
    let generatedPrompts: GeneratedPrompt[];
    try {
      generatedPrompts = await generatePromptsFromClient(
        masterContext,
        client.name,
        quantity
      );
    } catch (genErr) {
      console.error("[smart-batch] Prompt generation error:", genErr);
      return NextResponse.json(
        { error: `Failed to generate prompts: ${errMsg(genErr)}` },
        { status: 502 }
      );
    }

    // Limit to requested quantity
    const prompts = generatedPrompts.slice(0, quantity);

    if (prompts.length === 0) {
      return NextResponse.json(
        { error: "Failed to generate valid prompts from client data" },
        { status: 502 }
      );
    }

    // Create batch run (no prompt pack needed)
    let batchRun;
    try {
      batchRun = await createBatchRun({
        tenantId: auth.tenant.id,
        clientId: body.clientId,
        profileId: body.profileId,
        totalItems: prompts.length,
        createdBy: auth.user.id,
        // Ad angle engine metadata
        ...(selectedAngles.length > 0
          ? {
              metadata: JSON.stringify({ selectedAngles, lockAngles }),
            }
          : {}),
      });
    } catch (runErr) {
      console.error("[smart-batch] createBatchRun error:", runErr);
      return NextResponse.json(
        { error: `Failed to create batch run: ${errMsg(runErr)}` },
        { status: 500 }
      );
    }

    // Create batch items with brand-context-enhanced prompts
    const batchItems = prompts.map((item) => ({
      concept: item.concept,
      prompt: `${masterContext}\n\nGenerate creative for:\n${item.prompt_text}`,
    }));

    try {
      await createBatchItems(batchRun.id, batchItems);
    } catch (itemErr) {
      console.error("[smart-batch] createBatchItems error:", itemErr);
      return NextResponse.json(
        { error: `Failed to create batch items: ${errMsg(itemErr)}` },
        { status: 500 }
      );
    }

    // Trigger batch processing (fire-and-forget)
    const processUrl = new URL("/api/batch/process", request.url);
    fetch(processUrl.toString(), {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        runId: batchRun.id,
        tenantId: auth.tenant.id,
        profileId: body.profileId,
        clientId: body.clientId,
        aspectRatio: body.aspectRatio,
        resolution: body.resolution,
      }),
    }).catch((err) => {
      console.error(
        "[smart-batch] Failed to trigger batch processing:",
        err
      );
    });

    return NextResponse.json({ run: batchRun }, { status: 201 });
  } catch (error) {
    console.error("[smart-batch create] Unhandled error:", error);
    const message =
      error instanceof Error
        ? error.message
        : "Failed to create smart batch";
    return NextResponse.json({ error: message }, { status: 500 });
  }
}